### ISSUE TITLE
incompatible with composer 1.6.0

### ISSUE THREAD

**Issue by fritzmg** [contao-community-alliance/composer-client#315]
When using composer `1.6.0` the following error occurs:
```
Fatal error: Uncaught exception Error with message Class 'Composer\Factory' not found thrown in system\modules\!composer\src\ClientBackend.php on line 294

#0 system\modules\!composer\src\ClientBackend.php(125): ContaoCommunityAlliance\Contao\Composer\ClientBackend->loadComposer()
#1 system\modules\core\classes\Backend.php(423): ContaoCommunityAlliance\Contao\Composer\ClientBackend->generate()
#2 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('composer')
#3 contao\main.php(20): Contao\BackendMain->run()
#4 {main}
```

**Comment by discordier** [comment]
I have hat the same problem but deleting the `composer.phar` and all backup copies in `TL_ROOT/composer/` and re-downloading `composer.phar` fixed it for me.

I suppose the download was somehow corrupted.

**Comment by fritzmg** [comment]
Actually I was mistaken. The `composer-client` didn't download `1.6.0` (stable). It is downloading `1.7-dev`:
```
Composer version 1.7-dev (749b4c46b74f9702fc4f6abde6480fb6f0373ed6) 2018-01-04 11:22:11
```
Today, it is downloading the following version:
```
Composer version 1.7-dev (be040f8e3111b38c1e49ae5cd6b929dbf5c39045) 2018-01-05 07:41:58
```
which probably re-added the `Composer\Factory`.

So the actual problem is that the composer-client isn't downloading the latest stable release. Didn't we have this problem already?

**Comment by discordier** [comment]
We did long time ago, we added the "do not update composer.phar" option back then.

The problem is/was, that there is no "latest stable URL" and nobody ever implemented the list downloading and lookup of the latest phar to download.

**Comment by fritzmg** [comment]
> The problem is/was, that there is no "latest stable URL" and nobody ever implemented the list downloading and lookup of the latest phar to download.

There is now: https://getcomposer.org/composer-stable.phar
