### ISSUE TITLE
Problem to reach https://legacy-packages-via.contao-community-alliance.org with composer

### ISSUE THREAD

**Issue by akroii** [contao-community-alliance/composer-client#316]
Looks like there's problem with composer?
I'am getting this error when i type one or more words in composer search field.

```
Fatal error: Uncaught exception Composer\Downloader\TransportException with message The "https://legacy-packages-via.contao-community-alliance.org/search.json?q=news&type=" file could not be downloaded (HTTP/1.1 500 Internal Server Error) thrown in phar://composer/composer.phar/src/Composer/Util/RemoteFilesystem.php on line 373
#0 phar://composer/composer.phar/src/Composer/Util/RemoteFilesystem.php(101): Composer\Util\RemoteFilesystem->get('legacy-packages...', 'https://legacy-...', Array, NULL, false)
#1 phar://composer/composer.phar/src/Composer/Repository/ComposerRepository.php(203): Composer\Util\RemoteFilesystem->getContents('legacy-packages...', 'https://legacy-...', false)
#2 phar://composer/composer.phar/src/Composer/Repository/CompositeRepository.php(105): Composer\Repository\ComposerRepository->search('news', 0, NULL)
#3 system/modules/!composer/src/Controller/SearchController.php(95): Composer\Repository\CompositeRepository->search('news', 0)
#4 system/modules/!composer/src/Controller/SearchController.php(52): ContaoCommunityAlliance\Contao\Composer\Controller\SearchController->searchPackages(Array, 0)
#5 system/modules/!composer/src/ClientBackend.php(213): ContaoCommunityAlliance\Contao\Composer\Controller\SearchController->handle(Object(Contao\Input))
#6 system/modules/core/classes/Backend.php(423): ContaoCommunityAlliance\Contao\Composer\ClientBackend->generate()
#7 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('composer')
#8 contao/main.php(20): Contao\BackendMain->run()
#9 {main}
```

**Comment by fritzmg** [comment]
I can confirm the issue.

**Comment by discordier** [comment]
Totally missed this issue.
We had a brief downtime back then.

Next time please ping us (either me ([@discordier](https://twitter.com/discordier)) or [@frontendschlampe](https://twitter.com/hofffnungsvoll)) on twitter and we will respond briefly.
